
feature_engineering:
  min_ngrams: 1
  max_ngrams: 5
  strong_hashes:
    - "SHA-256"
    - "SHA-384"
    - "SHA-512"
    - "SHA-1"
    - "SHA-224"
  use_third_party_packages: False
  use_year: False
  use_tfidf: False
  min_document_frequency: 0.005
  max_document_frequency: 0.995
  input_json_path: "/path/to/cleaned.json"
  output_csv_path: Null

records_selection:
  input_csv_path: Null # csv from feature engineering
  train_set_ratio: 0.9 # ratio of dataset to use for training
  malware_detection:
    output_hdf_path: Null
  malware_labeling:
    output_hdf_path: Null
    family_count: 10
    group_rest: True
    families_to_exclude:
      - "UNKNOWN"
      - "BENIGN"

feature_scaling:
  normalize_by_class_count: True
  normalize_by_lines_of_code: False
  use_standard_scaling: False
  columns_to_ignore:
    - "metadata_source"
    - "metadata_dex_year"
    - "metadata_n_lines"
    - "metadata_n_classes"
  task_configs:
    malware_detection:
      input_hdf_path: Null # .h5 file with 'X_train', 'X_test', 'y_train', 'y_test' as keys
      output_hdf_path: Null
    malware_labeling:
      input_hdf_path: Null # .h5 file with 'X_train', 'X_test', 'y_train', 'y_test' as keys
      output_hdf_path: Null

feature_selection:
  max_iterations: 100
  use_weak_features_boruta: False
  n_trees: 200
  correlation_threshold: 0.95
  columns_to_ignore:
    - "metadata_source"
    - "metadata_dex_year"
    - "metadata_n_lines"
    - "metadata_n_classes"
  task_configs:
    malware_detection:
      input_hdf_path: Null # .h5 file with 'X_train', 'X_test', 'y_train', 'y_test' as keys
      output_hdf_path: "/path/to/output_hdf.h5"
    malware_labeling:
      input_hdf_path: Null # .h5 file with 'X_train', 'X_test', 'y_train', 'y_test' as keys
      output_hdf_path: "/path/to/output_hdf.h5"


