cleaning: # clean the dataset
  input_json_paths:
    - path: "/path/to/benign.json"
      benign: True
      source: "AndroZoo"
    - path: "/path/to/malicious.json"
      benign: False
      source: "AndroZoo" 
  output_json_path: Null # optional output path where to store the cleaned dataset, json
  labels: # cleaning of labels (if not defined then don't clean them)
    name_rules: # rules how to clean names
      appin: "appinventor"
      appinvent: "appinventor"
      autoins: "autoinst"
      badnewsn: "badnews"
      gingermaste: "gingermaster"
      hiddenap: "hiddenapp"
      hiddenapps: "hiddenapp"
      hiddenads: "hiddenad"
      plangton: "plankton"
      revmobads: "revmobad"
      smsspoofere: "smsspoofer"
      yuom: "yuomi"
    type_rules: # rules how to clean types
      trj: "trojan"
      troj: "trojan"
      trojansms: "smssend++trojan"
      spy: "spyware"
      fakeinst: "fakeinstall"
      drop: "dropper"
      click: "clicker"
      adsware: "adware"
      addware: "adware"
      smssender: "smssend"
      unclassifiedmalware: "UNKNOWN"
    names_to_ignore_during_mapping: # names which are supposed to be ignored when making sure the mapping name to type is one to one
      - "UNKNOWN" # ignore name unknown while calculating the most common name corresponding to each type
      - "BENIGN"
  remove_third_party_crypto_from_packages: True # whether to remove third party crypto libs from third party packages (duplicite info)
  remove_similar_records_classes: True # whether to remove similar classes (filenames)
  crypto_api_calls: # cleaning of crypto api calls (if not defined then don't clean them)
    remove_when_imports_empty: True
    remove_duplicates: True
    remove_false_positives: True
    calls_to_filter:
      - "Cipher"
      - "PRIVATE_KEY"
      - "SECRET_KEY"
      - "PUBLIC_KEY"
      - "ENCRYPT_MODE"

feature_engineering:
  min_ngrams: 1
  max_ngrams: 5
  strong_hashes:
    - "SHA-256"
    - "SHA-384"
    - "SHA-512"
    - "SHA-1"
    - "SHA-224"
  use_third_party_packages: False
  use_year: False
  use_tfidf: False
  min_document_frequency: 0.005
  max_document_frequency: 0.995
  input_json_path: Null
  output_csv_path: Null

records_selection:
  input_csv_path: Null # csv from feature engineering
  train_set_ratio: 0.9 # ratio of dataset to use for training
  malware_detection:
    output_hdf_path: "/path/to/output_hdf.h5"
  malware_labeling:
    output_hdf_path: "/path/to/output_hdf.h5"
    family_count: 10
    group_rest: True
    families_to_exclude:
      - "UNKNOWN"
      - "BENIGN"

