# Note: this is currently supposed to be only supported for Tree Based models, specifically Random Forest.

# parameters related to input
model_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/results/models/malware_detection/rf.joblib" # pickle or joblib
values_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/data/prepared/malware_detection/test_X.csv" # path to features, set that was NOT used to train the model should be used (validation/test)
target_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/data/prepared/malware_detection/test_y.csv" # optional path to csv targets, this has to have the same amount of rows as values_path!!
sample_size: 10000 # sample size to draw, in case of non-positive number or number bigger than values use it all
indices: Null # optional list of indices to use, for example "0:1000" use samples with indices from 0 to 1000
# Note: indices is applied after drawing a sample of sample_size! (Thus, both can be used, although using only one makes sense)

# parameters that change calculations
feature_perturbation: "tree_path_dependent" # "interventional" or "tree_path_dependent" - please refer to TreeExplainer documentation
model_output: "raw" # what output of the model should be explained, "raw"/"probability"/"log_loss" - see TreeExplainer docs
approximate: False # when True the method is faster but might be slower. See TreeExplainer documentation.
calculate_shap_values: True
calculate_interaction_values: False

save_values: True # whether to save values - this might be useless when whole dataset is used
save_targets: True # wheter to save targets - this might be useless when whole dataset is used
save_hashes: True # whether to save hashes of used samples

output_path: "/var/tmp/xmacko1/bachelor_thesis/repos/AndroidMalwareLabeling/results/explainability/malware_detection/rf_10k.h5"
# save the output into a single h5 file in this format:
# keys: 
#   - shap_values             - dataframe of shap values
#   - shap_interaction_values - dataframe of shap interaction values
#   - values                  - dataframe of values used
#   - shap_expected_values    - dataframe (series because only one column) of shap expected values
#   - targets                 - dataframe (series because only one column) of targets, not saved if target_path is Null
#   - hashes                  - dataframe (series because only one column) of hashes
output_explainer_path: Null # optional path to save explainer to

