# This is an example of a configuration file for `cli_prepare.py`.

# The whole preparation pipeline is in the given order: cleaning -> records_selection -> feature_engineering -> feature_selection

# Some of the steps from the beginning or the end can be skipped, however no step can't be skipped "from the middle".
# Valid approaches where the input paths are specified for the first step that is defined:
#   - cleaning
#   - cleaning -> records_selection
#   - feature_engineering -> feature_selection
#   - ...
# Invalid approaches even with input paths specified for the first step:
#   - cleaning -> feature_engineering
#   - records_selection -> feature_selection
#   - ...

# Optionally, each step that is not the last one can have defined output paths if the some of the results are wanted.
# For example, it could be useful to store the dataset after feature selection but also after records selection.
# And later on when there are changes to feature engineering then the cleaning and records selection can be safely skipped.

# Please note that input paths are completely ignored except for the first step in the pipeline used in the given config.
# For example, ignore input paths for everything except cleaning when cleaning is defined.


cleaning: # clean the dataset
  input_paths:
    - path: "/path/to/benign.json"
      benign: True
      source: "AndroZoo"
    - path: "/path/to/malicious.json"
      benign: False
      source: "AndroZoo" 
  output_path: Null # optional output path where to store the cleaned dataset, json
  labels: # cleaning of labels (if not defined then don't clean them)
    name_rules: # rules how to clean names
      appin: "appinventor"
      appinvent: "appinventor"
      autoins: "autoinst"
      badnewsn: "badnews"
      gingermaste: "gingermaster"
      hiddenap: "hiddenapp"
      hiddenapps: "hiddenapp"
      hiddenads: "hiddenad"
      plangton: "plankton"
      revmobads: "revmobad"
      smsspoofere: "smsspoofer"
      yuom: "yuomi"
    type_rules: # rules how to clean types
      trj: "trojan"
      troj: "trojan"
      trojansms: "smssend++trojan"
      spy: "spyware"
      fakeinst: "fakeinstall"
      drop: "dropper"
      click: "clicker"
      adsware: "adware"
      addware: "adware"
      smssender: "smssend"
      unclassifiedmalware: "UNKNOWN"
    names_to_ignore_during_mapping: # names which are supposed to be ignored when making sure the mapping name to type is one to one
      - "UNKNOWN" # ignore name unknown while calculating the most common name corresponding to each type
      - "BENIGN"
  remove_third_party_crypto_from_packages: True # whether to remove third party crypto libs from third party packages (duplicite info)
  remove_similar_records_classes: True # whether to remove similar classes (filenames)
  crypto_api_calls: # cleaning of crypto api calls (if not defined then don't clean them)
    remove_when_imports_empty: True
    remove_duplicates: True
    remove_false_positives: True
    calls_to_filter: # API calls which should be filtered out if false positives are beign removed
      - "Cipher"
      - "PRIVATE_KEY"
      - "SECRET_KEY"
      - "PUBLIC_KEY"
      - "ENCRYPT_MODE"

records_selection:
  input_path: Null # json from cleaning
  malware_detection:
    output_features_path: Null # json
    output_target_path: Null # json
  malware_labeling:
    output_features_path: Null # json
    output_target_path: Null # json
    family_count: 10 # count of families to extract
    group_rest: True # whether to group the rest families into class OTHER
    families_to_exclude: # drop samples with these families
      - "UNKNOWN"
      - "BENIGN"

feature_engineering:
  train_set_ratio: 0.9
  min_ngrams: 1
  max_ngrams: 5
  strong_hashes:
    - "SHA-256"
    - "SHA-384"
    - "SHA-512"
    - "SHA-1"
    - "SHA-224"
  use_third_party_packages: False
  use_year: False
  use_tfidf: False
  min_document_frequency: 0.005
  max_document_frequency: 0.995
  normalize_by_class_count: True # whether to normalize the count features by overall class count
  scale_features: True # whether to use standard scaling
  task_configs:
    malware_detection:
      input_features_path: Null # json from records selection
      input_target_path: Null # json from records selection
      output_hdf_path: Null # hdf
    malware_labeling:
      input_features_path: Null # json from records selection
      input_target_path: Null # json from records selection
      output_hdf_path: Null # hdf

feature_selection:
  max_iterations: 100
  use_weak_features_boruta: False # whether to also use tentative (not strong) features
  n_trees: 200 # count of trees
  correlation_threshold: 0.95 # correlation threshold to filter correlated features on
  task_configs:
    malware_detection:
      input_hdf_path: Null # .h5 file with 'X_train', 'X_test', 'y_train', 'y_test' as keys
      output_hdf_path: "/path/to/output_hdf.h5"
    malware_labeling:
      input_hdf_path: Null # .h5 file with 'X_train', 'X_test', 'y_train', 'y_test' as keys
      output_hdf_path: "/path/to/output_hdf.h5"


