# This is a sample meta.yml based on which the dataset is parsed. It will get created automatically.

apk_available: false # Set automatically, False by default
dataset_name: Baby dataset
description: Baby dataset
dx_available: false # Set automatically, False by default
n_samples: 0 # Set automatically, False by default
