apk_available: false
dataset_name: Pick your dataset name here
description: Put your dataset description here
dx_available: false
n_samples: 10
sha256_digest: 9b63939c0afaeae273015f9346423e9e7def46aeae361a9291d13f87aa309dde
