threads: 8 # threads to use for a single model
cv_splits: 5 # cross validation splits
input_hdf_path: "/path/to/prepared_data.h5" # path to prepared data with X_train, X_test, and y_test as dataframes
columns_to_ignore: # Columns to ignore during draining - "source" should be always here!
  - "metadata_source"
  - "metadata_dex_year"
  - "metadata_n_lines"
  - "metadata_n_classes"
task_configs: # for supported keys check constants in training/api.py atm
  rf: # random forest
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  lgbm: # LGBM
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  svm: # Linear Support Vector Machines
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  gnb: # Gaussian Naive Bayes
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  cnb: # Complement Naive Bayes
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  lda: # Linear Discriminant Analysis
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  ebm: # explainable boosting
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  rules: # decision rule list
    output_model_path: Null # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  