threads: 4 # threads to use for a single model
cv_splits: 10 # cross validation splits
input_hdf_path: "data/malware_detection_full.h5" # path to prepared data with X_train, X_test, and y_test as dataframes
columns_to_ignore: # Columns to ignore during draining - "source" should be always here!
  - "metadata_source"
  - "metadata_dex_year"
  - "metadata_n_lines"
  - "metadata_n_classes"
task_configs: # for supported keys check constants in training/api.py atm
  rf: # random forest
    output_model_path: "data/malware_detection_rf.joblib" # stored as pickle object using joblib
    output_prediction_path: Null # optional test csv output prediction path, not used if input_test_features_path is undefined
  